<!doctype html>
<html lang="zh">

<head>
    <title></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <script src="<?php echo YUrl::assets('editor','','/jquery.min.js');?>"></script>

    <script src="<?php echo YUrl::assets('editor','','/editormd.min.js') ;?>"></script>

    <script src="<?php echo YUrl::assets('editor','lib','/marked.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/prettify.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/raphael.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/underscore.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/sequence-diagram.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/flowchart.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/jquery.flowchart.min.js') ;?>"></script>



    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','bootstrap/css/bootstrap.min.css');?>">

    <link rel="stylesheet" href="<?php echo YUrl::assets('editor','css','editormd.css');?>" />

    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','/font-awesome/css/font-awesome.min.css');?>">
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','/linearicons/style.css');?>">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','main.css');?>">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','demo.css');?>">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo YUrl::assets('admin','img','/apple-icon.png');?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo YUrl::assets('admin','img','/favicon.png');?>">
    <link href="<?php echo YUrl::assets('static','md','/css/editormd.min.css')?>" rel="stylesheet" />
</head>
<body>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">添加文章</h3>
    </div>
    <div class="panel-body">
        <form class="form-auth-small" method="post" action="">
        <span class="panel-title">标题</>
        <input type="text" name="title" class="form-control" placeholder="title">
        <br>
        <span class="panel-title">副标题</>
        <input type="text" name="subtitle" class="form-control" placeholder="subtitle">
        <br>
        <span class="panel-title">分类</>
        <select name='type' class="form-control">
            <option value="cheese">Cheese</option>
            <option value="tomatoes">Tomatoes</option>
            <option value="mozarella">Mozzarella</option>
            <option value="mushrooms">Mushrooms</option>
            <option value="pepperoni">Pepperoni</option>
            <option value="onions">Onions</option>
        </select>
        <br>
        <span class="panel-title">文章内容</>

        <div id="article">
                <textarea name='article' style="display:none;"></textarea>
        </div>
        <br>
        </form>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button onclick="putUp()" type="button" class="btn btn-primary btn-block">提交</button>
        </div>
    </div>
</div>



<!-- END WRAPPER -->
<!-- Javascript -->



<script src="<?php echo YUrl::assets('admin','vendor','/bootstrap/js/bootstrap.min.js');?>"></script>
<script src="<?php echo YUrl::assets('admin','vendor','/jquery-slimscroll/jquery.slimscroll.min.js');?>"></script>
<script src="<?php echo YUrl::assets('admin','scripts','klorofil-common.js');?>"></script>
<script type="text/javascript">

    $(function() {

        testeditormd = editormd("article", {
            width : '100%',
            height : 640,
            syncScrolling : "single",
            path : "<?php echo YUrl::assets('editor','','lib').'/'?>",
            imageUpload    : true,
            imageFormats   : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "",
            saveHTMLToTextarea : true,
        });

    });
    function putUp(){
        $('form').submit();
    }

</script>


</body>

</html>
