<!doctype html>
<html lang="zh">

<head>
    <title></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->




    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','bootstrap/css/bootstrap.min.css');?>">

    <link rel="stylesheet" href="<?php echo YUrl::assets('editor','css','editormd.css');?>" />

    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','/font-awesome/css/font-awesome.min.css');?>">
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','/linearicons/style.css');?>">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','main.css');?>">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','demo.css');?>">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo YUrl::assets('admin','img','/apple-icon.png');?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo YUrl::assets('admin','img','/favicon.png');?>">
    <link href="<?php echo YUrl::assets('static','md','/css/editormd.min.css')?>" rel="stylesheet" />
</head>
<body>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">添加标签</h3>
    </div>
    <div class="panel-body">
        <form class="form-auth-small" method="post" action="">
            <span class="panel-title">标签名</>
            <input type="text" name="tagname" class="form-control" placeholder="title">
            <br>
            <span class="panel-title">所属标签</>
            <select name='pid' class="form-control">
                <option value="0">总标签</option>
                <?php
                    foreach($info as $val){
                        echo " <option value=$val[id]>$val[level]$val[tagname]</option>";
                    }
                ?>
            </select>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary btn-block">提交</button>

                </div>
            </div>

        </form>
    </div>

</div>


<!-- END WRAPPER -->
<!-- Javascript -->



<script src="<?php echo YUrl::assets('admin','vendor','/bootstrap/js/bootstrap.min.js');?>"></script>
<script src="<?php echo YUrl::assets('admin','vendor','/jquery-slimscroll/jquery.slimscroll.min.js');?>"></script>
<script src="<?php echo YUrl::assets('admin','scripts','klorofil-common.js');?>"></script>



</body>

</html>
