<aside class="col-md-4">
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">搜索</h3>
        <div style="width: 200px;" class="input-group">
            <input class="form-control" type="text" name="search">
            <span class="input-group-btn"><button style="border-color: black" class="btn" type="button">搜索</button></span>
        </div>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">时间</h3>
        <ul>
            <li>
                <a href="#">2018-10</a>
            </li>

        </ul>
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">标签</h3>
        <ul>
            <li>
                <a href="#">php</a>
            </li>

        </ul>
    </div>
</aside>