
<!doctype html>
<html lang="en" class="fullscreen-bg">

<head>
    <script  src="<?php echo YUrl::assets('admin','vendor','/jquery/jquery.js')?>"></script>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <title>Register</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','/bootstrap.min.css')?>">
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','/font-awesome/css/font-awesome.min.css')?>">
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','vendor','/linearicons/style.css')?>">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','/main.css')?>">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="<?php echo YUrl::assets('admin','css','/demo.css')?>">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo YUrl::assets('admin','img','/apple-icon.png')?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo YUrl::assets('admin','img','/favicon.png')?>">
</head>

<body>
<!-- WRAPPER -->
<div id="wrapper">
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
            <div class="auth-box ">
                <div class="left">
                    <div class="content">
                        <div class="header">
                            <p class="lead">注册</p>
                        </div>
                        <form class="form-auth-small" action="" method="post">
                            <div class="form-group">
                                <label for="signin-email" class="control-label sr-only">Email</label>
                                <input type="text" class="form-control" name="username"  placeholder="用户名" onblur="checkName()">

                            </div>
                            <span id='userNotice' style="color: red;font-size: 14px;float: left;"></span>
                            <div class="form-group">
                                <label for="signin-password" class="control-label sr-only">Password</label>
                                <input onblur="checkPass()" type="password" class="form-control" name="password" value="" placeholder="密码">
                            </div>
                            <span id='passNotice' style="color: red;font-size: 14px;float: left;"></span>
                            <div class="form-group">
                                <label for="signin-password" class="control-label sr-only">Password</label>
                                <input onblur="checkSame()" type="password" class="form-control" name="passwordCheck" value="" placeholder="确认密码">
                            </div>
                            <span id='sameNotice' style="color: red;font-size: 14px;float: left;"></span>
                             <div class="form-group">
                                <label for="signin-password" class="control-label sr-only">Password</label>
                                <input onblur="checkCode()  " type="text" class="form-control" name="code" value="" placeholder="注册码">
                            </div>
                            <span id='codeNotice' style="color: red;font-size: 14px;float: left;"></span>
                            <button onclick="checkSubmitInfo()"  type="button" class="btn btn-primary btn-lg btn-block">注册</button>
                            <input type="hidden" value="false" id="status">
                        </form>
                    </div>
                </div>
                <div class="right">
                    <div class="overlay"></div>
                    <div class="content text">
                        <span class="heading" style="font-size: medium">今天一天过得不错吧？<br />梦想是不是更远了？</span>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!-- END WRAPPER -->

<script>
    function checkName(){
        var username = $("input[name='username']").val();
        //检测合法性
        var regex = /^[A-Za-z]{1}[A-Za-z\d]{3,7}$/;
        var msg = false;
        if(username.match(regex) == null){
            msg = '用户名必须以字母开头，并且在5-8位字符之间';
        }
        //检测重复性

        $.ajax({
            url:"/admin/Register/ajaxCheck",    //请求的url地址
            async:true,//请求是否异步，默认为异步，这也是ajax重要特性
            data:{"name":username},    //参数值,键值对
            type:"POST",   //请求方式
            beforeSend:function(){
                //请求前的处理
            },
            success:function(req){
                //请求成功时处理
                if(req != ''){
                    notice('userNotice',req)
                }
            },
            complete:function(){
                //请求完成的处理
            },
            error:function(){
                //请求出错处理
            }
        });
        notice('userNotice',msg)
    }
    function checkPass() {
        var regex = /^[A-Z]{1}[A-Za-z\d\@]{4,9}$/;
        var password = $("input[name='password']").val();
        var msg = false;
       if(password.match(regex) == null){
           msg = '密码必须以大写字母开头，并且在5-10位字符之间';
       }

       notice('passNotice',msg)
    }
    function checkSame(){
        var password = $("input[name='password']").val();
        var passwordSame = $("input[name='passwordCheck']").val();
        var msg = false;
        if(password != passwordSame){
            msg = '俩次输入的密码不一致。'
        }
        notice('sameNotice',msg)
    }
    function checkCode(){
        var code = $("input[name='code']").val();
        var msg = false;
        if(code == ''){
            msg = '注册码不能为空';
        }
        notice('codeNotice',msg);
    }
    function notice(id,msg){
        if(msg == false){
            $('#'+id).html();
        }
        $('#'+id).html(msg);
    }
    function checkSubmitInfo(){
        var username = $("input[name='username']").val();
        var password = $("input[name='password']").val();
        var passwordSame = $("input[name='passwordCheck']").val();
        var code = $("input[name='code']").val();
        var userNotice = $('#userNotice').html();
        var passNotice = $('#passNotice').html();
        var sameNotice = $('#sameNotice').html();
        var codeNotice = $('#codeNotice').html();
        if(username==''||password==''||passwordSame==''||code==''){
            alert('信息不能为空');
            return;
        }
        if(userNotice !=''||passNotice != ''|| sameNotice !=''||codeNotice !=''){
            alert('请按规则填写信息！');
            return;
        }
        if(window.confirm('请核对路由配置数据正确，如无误请点确认，否则，请点取消！')){
            $('form').submit();
        }else{
            return false;
        }
    }

</script>
</body>

</html>
