<?php
require (APP_ROOT .'/application/library/common/Yurl.php');
$model = new YUrl();
?>
<!doctype html>
<html lang="en" class="fullscreen-bg">
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="<?php echo $model::assets('admin','css','/bootstrap.min.css')?>">
    <link rel="stylesheet" href="<?php echo $model::assets('admin','vendor','/font-awesome/css/font-awesome.min.css')?>">
    <link rel="stylesheet" href="<?php echo $model::assets('admin','vendor','/linearicons/style.css')?>">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="<?php echo $model::assets('admin','css','/main.css')?>">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="<?php echo $model::assets('admin','css','/demo.css')?>">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $model::assets('admin','img','/apple-icon.png')?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $model::assets('admin','img','/favicon.png')?>">
</head>

<body>
<!-- WRAPPER -->
<div id="wrapper">
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
            <div class="auth-box ">
                <div class="left">
                    <div class="content">
                        <div class="header">

                            <p class="lead">登录</p>
                        </div>
                        <form class="form-auth-small" action="" method="post">
                            <div class="form-group">
                                <label for="signin-email" class="control-label sr-only">Email</label>
                                <input type="text"  class="form-control" name="username" value="" placeholder="用户名">
                            </div>
                            <div class="form-group">
                                <label for="signin-password" class="control-label sr-only">Password</label>
                                <input type="password" class="form-control" name="password" value="" placeholder="密码">
                            </div>
                            <div class="form-group clearfix">
                                <label class="fancy-checkbox element-left">
                                    <input type="checkbox" name="remember">
                                    <span>记住账号</span>
                                </label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-lg btn-block">登录</button>

                        </form>
                    </div>
                </div>
                <div class="right">
                    <div class="overlay"></div>
                    <div class="content text">
                        <span class="heading" style="font-size: medium">生活不止眼前的苟且，<br />还有明天的苟且和后天的苟且。</span>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

<!-- END WRAPPER -->
</body>

</html>

