<?php
@\Yaf\Loader::import(APP_ROOT.'/application/modules/Web/views/common/header.phtml');
?>
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="<?php echo YUrl::assets('editor','','/jquery.min.js');?>"></script>

    <script src="<?php echo YUrl::assets('editor','','/editormd.min.js') ;?>"></script>

    <script src="<?php echo YUrl::assets('editor','lib','/marked.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/prettify.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/raphael.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/underscore.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/sequence-diagram.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/flowchart.min.js') ;?>"></script>
    <script src="<?php echo YUrl::assets('editor','lib','/jquery.flowchart.min.js') ;?>"></script>

    <!-- css -->
<!--    <link rel="stylesheet" href= "APP_ROOT/public/css/bootstrap.min.css">-->
    <link rel="stylesheet" href= "<?php echo YUrl::assets('web','css','/bootstrap.min.css')?>">
    <link rel="stylesheet" href="<?php echo YUrl::assets('web','css','/pace.css')?>">
    <link rel="stylesheet" href="<?php echo YUrl::assets('web','css','/custom.css')?>">

    <!-- js -->

    <script src="<?php echo YUrl::assets('web','js','/bootstrap.min.js')?>"></script>
    <script src="<?php echo YUrl::assets('web','js','/pace.min.js')?>"></script>
    <script src="<?php echo YUrl::assets('web','js','/modernizr.custom.js')?>"></script>
</head>

<body>



<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                <?php
                    foreach($list as $k=>$val){?>
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="single.html"><?php echo $val['title']?> </a>
                        </h1>
                        <div class="entry-meta">
                            <time style="color: black;" ><?php echo date('Y-m-d')?></time>
                        </div>
                    </header>
                    <div style="overflow: hidden;height: 150px">
                        <div id="doc-content<?php echo $k?>">
                            <textarea style="display:none;"><?php echo $val['content']?></textarea>
                        </div>
                    </div>

                    <div class="read-more cl-effect-14">
                        <a href="#" class="more-link">阅读 <span class="meta-nav"></span></a>
                    </div>
                </article>
                    <?php }
                ?>


            </main>
            <?php
            @\Yaf\Loader::import(APP_ROOT.'/application/modules/Web/views/common/right.phtml');
            ?>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="full-width.html">Blog</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
</div>


<script src="<?php echo YUrl::assets('web','js','/script.js')?>"></script>
<script>

    $(function () {
        editormd.markdownToHTML("doc-content2", {//注意：这里是上面DIV的id
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList: true,
            tocm: true,
            tex: true, // 默认不解析
            flowChart: true, // 默认不解析
            sequenceDiagram: true, // 默认不解析
            codeFold: true
        });
        editormd.markdownToHTML("doc-content1", {//注意：这里是上面DIV的id
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList: true,
            tocm: true,
            tex: true, // 默认不解析
            flowChart: true, // 默认不解析
            sequenceDiagram: true, // 默认不解析
            codeFold: true
        });
        editormd.markdownToHTML("doc-content0", {//注意：这里是上面DIV的id
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList: true,
            tocm: true,
            tex: true, // 默认不解析
            flowChart: true, // 默认不解析
            sequenceDiagram: true, // 默认不解析
            codeFold: true
        });

        ;});

</script>
</body>
</html>
