<!doctype html>
<html lang="en" class="fullscreen-bg">

<head>
    <title>Lockscreen</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="<?php echo \common\YUrl::assets('admin','vendor','/bootstrap/css/bootstrap.min.css')?>">
    <link rel="stylesheet" href="<?php echo \common\YUrl::assets('admin','vendor','/font-awesome/css/font-awesome.min.css')?>">
    <link rel="stylesheet" href="<?php echo \common\YUrl::assets('admin','vendor','/linearicons/style.css')?>">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="<?php echo \common\YUrl::assets('admin','css','/main.css')?>">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="<?php echo \common\YUrl::assets('admin','css','/demo.css')?>">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <script  src="<?php echo \common\YUrl::assets('admin','vendor','/jquery/jquery.js')?>"></script>
</head>
<body>
<!-- WRAPPER -->
<div id="wrapper">
    <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
            <div class="auth-box lockscreen clearfix">
                <div class="content">
                    <h1><?php echo $message?></h1>
                    <span style="font-size: medium">马上为您跳转</span>
                    <span> </span>
                    <div>
                        <span id="second" style="font-size: large"><?php echo  $second?></span>
                        <span>秒后跳转至</span>
                        <span><a id='url' href="<?php echo $url?>">页面</a></span>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
<!-- END WRAPPER -->
</body>
<script>
    $(function () {
        var wait = $('#second').html();
        var herf = $('#url').attr('href');
        var interval = setInterval(
            function () {
                var time = --wait;
                $('#second').html(time);
                if(time <= 0) {
                    window.location.href = herf;
                    clearInterval(interval);
                };
            },1000
        );
    })
</script>
</html>
